apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redops.fullname" . }}-secrets
  labels:
    {{- include "redops.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-host: {{ .Values.secrets.dbHost | quote }}
  db-password: {{ .Values.secrets.dbPassword | quote }}
  redis-host: {{ .Values.secrets.redisHost | quote }}
  app-secret-key: {{ .Values.secrets.appSecretKey | quote }}
