apiVersion: v1
kind: Secret
metadata:
  name: redops-secrets
  namespace: redops
type: Opaque
stringData:
  db-host: "postgres.redops.svc.cluster.local"
  db-password: "CHANGE_ME"
  redis-host: "redis.redops.svc.cluster.local"
  app-secret-key: "CHANGE_ME_TO_RANDOM_64_CHARS"
  github-client-id: ""
  github-client-secret: ""
  google-client-id: ""
  google-client-secret: ""
